In [2]:
import tensorflow as tf
import numpy as np

x = tf.constant(np.arange(60.),shape=[3,4,5],dtype=tf.float32)    
with tf.Session() as sess:
    print(x.eval())

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]


In [12]:
import tensorflow as tf

s = x.get_shape()
s2 = x.get_shape().as_list()
print(type(s))
print(s)

print()

s2 = x.get_shape().as_list()
print(type(s2))
print(s2)

print()

result_w = x.shape[1]
result_h = x.shape[2]
x3 = result_w * result_h
print(result_w)
print(result_h)
print(x3.value)
print(type(x3))
print(type(x3.value))

<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
(3, 4, 5)

<class 'list'>
[3, 4, 5]

4
5
20
<class 'tensorflow.python.framework.tensor_shape.Dimension'>
<class 'int'>


### argmin argmax

#### 次数1の場合，行ごと最大の値の添字になる

In [10]:
import tensorflow as tf
import numpy as np

sess = tf.Session()
Y = np.array([[0.1, 0.2, 0.3, 0.4],
              [0.0, 0.8, 0.2, 0.0],
              [0.0, 0.4, 0.5, 0.1]
             ])
sess.run(tf.argmax(Y, 1))

array([3, 1, 2])

### tf.equal()

#### 渡されたベクトルが一致しているか否かを見る

In [16]:
import tensorflow as tf
import numpy as np

sess = tf.Session()
Y = np.array([[0.1, 0.2, 0.3, 0.4],
              [0.0, 0.8, 0.2, 0.0],
              [0.0, 0.4, 0.5, 0.1]
             ])

Y_ = np.array([[0, 0, 0, 1],
              [0, 0, 0, 1],
              [0, 0, 0, 1]
             ])

sess.run(tf.equal(tf.argmax(Y, 1), tf.argmax(Y_, 1)))

array([ True, False, False])

### tf.cast()

#### tf.cast(変換したいもの，変換後の型)

In [28]:
import tensorflow as tf
import numpy as np

sess = tf.Session()
predict = np.array([ True, False, False])

sess.run(tf.cast(predict, tf.float32))
#print(sess.run(tf.cast(predict, tf.float32)))

array([1., 0., 0.], dtype=float32)

### tf.reduce_mean()

#### 与えたリストに入っている数値の平均を求める関数

In [24]:
import tensorflow as tf
import numpy as np

sess = tf.Session()
predict = np.array([ True, False, False])
correct_prediction = tf.cast(predict, tf.float32)
accuracy = tf.reduce_mean(correct_prediction)
sess.run(accuracy)

0.33333334

### np.split()

In [56]:
import numpy as np

x = np.arange(9.0)
print(x)

y = np.split(x, 3)
print(y)
print()
z = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17],[18,19,20,21,22,23],[24,25,26,27,28,29],[30,31,32,33,34,35]])
zz = np.split(z, 3)
zzz = np.split(z, [4])
print(zz)
print()
print(zzz)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])]

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])]


### np.eye()

#### 単位行列を生成するnumpyのAPI

In [66]:
import numpy as np

z = [1,2,3,4,5,6,7,8,9,10]
zy =[1,5,6,3,2,4,10,9,6,8]

z1, z2 = np.split(zy, [2])

print(z1)
print(z2)
print()

mz = np.max(z1)
print(mz)
print()

zzz = np.eye(np.max(z1)+1)[z1]
zzz

[1 5]
[ 6  3  2  4 10  9  6  8]

5



array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [5]:
import numpy as np

umo = np.mat(np.eye(1))
umo

matrix([[1.]])

### np.random.permutation()

In [91]:
import numpy as np
N=10
x = np.random.permutation(N)

print(x)

[8 6 7 9 3 1 0 4 2 5]


### np.matrix()

In [138]:
import numpy as np

m = np.matrix([[1,2],[3,4]])
print(m)
print()
m_to=m*m
print("matrix同士の積\n%s\n" %m_to)

a = np.matrix(m)
a[0,0]=6
print(a)
print()
print("aに変更を加えた後のm")
print(m)

[[1 2]
 [3 4]]

matrix同士の積
[[ 7 10]
 [15 22]]

[[6 2]
 [3 4]]

aに変更を加えた後のm
[[1 2]
 [3 4]]


### np.mat()

In [139]:
import numpy as np

m = np.mat([[1,2],[3,4]])
print(m)
print()
m_to=m*m
print("mat同士の積\n%s\n" %m_to)

a = np.mat(m)
a[0,0]=6
print(a)
print()
print("aに変更を加えた後のm")
print(m)

[[1 2]
 [3 4]]

mat同士の積
[[ 7 10]
 [15 22]]

[[6 2]
 [3 4]]

aに変更を加えた後のm
[[6 2]
 [3 4]]


### np.array()

In [140]:
import numpy as np

m = np.array([[1,2],[3,4]])
print(m)
print()
m_to=m*m
print("array同士の積\n%s\n" %m_to)

a = np.array(m)
a[0,0]=6
print(a)
print()
print("aに変更を加えた後のm")
print(m)

[[1 2]
 [3 4]]

array同士の積
[[ 1  4]
 [ 9 16]]

[[6 2]
 [3 4]]

aに変更を加えた後のm
[[1 2]
 [3 4]]


### np.random.rand()

In [32]:
import numpy as np
v = np.random.rand(2, 1)
print(v)
print()

a = np.random.rand(2, 2)
print(a)
print()

a_d = (a + a.T)/2
print(a_d)

[[0.10574885]
 [0.15900077]]

[[0.06311785 0.5307989 ]
 [0.85281309 0.14795047]]

[[0.06311785 0.69180599]
 [0.69180599 0.14795047]]


### range()

In [41]:
import numpy as np

a = np.arange(20)
print(a)
print()

T = len(a)
for t in range(T-1, 0, -1):
    
    print(a[t],"+",a[t-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

19 + 18
18 + 17
17 + 16
16 + 15
15 + 14
14 + 13
13 + 12
12 + 11
11 + 10
10 + 9
9 + 8
8 + 7
7 + 6
6 + 5
5 + 4
4 + 3
3 + 2
2 + 1
1 + 0


### np.eye(*A.shape)

#### *はタプル型を整数型に変える　ただし，タプルやリスト，print()外で用いることはできない．

In [65]:
import numpy as np

A = np.random.rand(2, 2)
print(A)
print()

#I = np.mat(np.eye(*A.shape))
I = np.eye(*A.shape)

print(I)
print()

As = A.shape
print(As)
print(*A.shape)
print()

x =(1,2,3,4)
print(x)
print(*x)

[[0.24091827 0.86837033]
 [0.93962429 0.08997648]]

[[1. 0.]
 [0. 1.]]

(2, 2)
2 2

(1, 2, 3, 4)
1 2 3 4


[1, 2, 3, 4]

### np.eye() NO.2

In [67]:
import numpy as np

n = np.eye(2,2)
n

array([[1., 0.],
       [0., 1.]])

### os.path.isdir()　os.path.exists()　&　os.makedirs()

#### ディレクトリ内にパスが存在するかどうか調べる． &　ディレクトリを作る

In [3]:
import os

path = './tmp/'
print(os.path.isdir(path))
print(os.path.exists(path))

True
True


In [4]:
import os

path = './model/'
if not os.path.isdir(path):
    os.makedirs(path)

### tf.get_variable()

In [6]:
import tensorflow as tf

unit=3

w = tf.get_variable("w", shape=[3], initializer = tf.zeros_initializer)
print(w)

<tf.Variable 'w:0' shape=(3,) dtype=float32_ref>


### []の演算

In [29]:
import numpy as np

a = [1 for i in range(10)]
b = [i for i in range(10)]
c = a + b
c

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### ndarrayの演算

In [26]:
import numpy as np

a = np.array([1 for i in range(10)])
b = np.array([i for i in range(10)])
c = a + b
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### []とndarrayの演算

In [7]:
import numpy as np

a = [1 for i in range(10)]
b = np.array([i for i in range(10)])
c = a + b
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### []の分割

In [25]:
cp,cl = c[:15],c[15:20]
print(cp)
print(cl)
cp

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 3, 4]

### ndarryの分割

In [27]:
import numpy as np

cp,cl = c[:5],c[5:10]
print(cp)
print(cl)
cp

[1 2 3 4 5]
[ 6  7  8  9 10]


array([1, 2, 3, 4, 5])

### ndarryからリスト

In [34]:
import numpy as np

a1 = np.arange(10)
print(a1)

a1_list = a1.tolist()
print(a1_list)

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### np.random.randn()

In [43]:
import numpy as np

a = np.random.rand(1)[0]
a

0.9801141969171291

In [57]:
b = [ [i] for i in range(10)]
print(b)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]


In [58]:
a = np.random.rand(10)
a + b

array([[0.58048319, 0.67797897, 0.14728988, 0.63952012, 0.82254926,
        0.46280213, 0.28673355, 0.12743203, 0.40638802, 0.50241411],
       [1.58048319, 1.67797897, 1.14728988, 1.63952012, 1.82254926,
        1.46280213, 1.28673355, 1.12743203, 1.40638802, 1.50241411],
       [2.58048319, 2.67797897, 2.14728988, 2.63952012, 2.82254926,
        2.46280213, 2.28673355, 2.12743203, 2.40638802, 2.50241411],
       [3.58048319, 3.67797897, 3.14728988, 3.63952012, 3.82254926,
        3.46280213, 3.28673355, 3.12743203, 3.40638802, 3.50241411],
       [4.58048319, 4.67797897, 4.14728988, 4.63952012, 4.82254926,
        4.46280213, 4.28673355, 4.12743203, 4.40638802, 4.50241411],
       [5.58048319, 5.67797897, 5.14728988, 5.63952012, 5.82254926,
        5.46280213, 5.28673355, 5.12743203, 5.40638802, 5.50241411],
       [6.58048319, 6.67797897, 6.14728988, 6.63952012, 6.82254926,
        6.46280213, 6.28673355, 6.12743203, 6.40638802, 6.50241411],
       [7.58048319, 7.67797897, 7.1472898

In [68]:
b = [ [i] for i in range(10)]
print(b)

a = np.random.rand(10).tolist()
print(a)

for i in range(len(b)):
    b[i][0] = b[i][0] + a[i]
print(b)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]
[0.9164235977441274, 0.9570093324073008, 0.40969088279178256, 0.16023747438482872, 0.10797131559675888, 0.11525716178411116, 0.4797814886058144, 0.5452650147137486, 0.06867179176720817, 0.32976346641583076]
[[0.9164235977441274], [1.9570093324073008], [2.4096908827917827], [3.1602374743848287], [4.1079713155967585], [5.115257161784111], [6.4797814886058145], [7.545265014713749], [8.068671791767208], [9.32976346641583]]


### 多変量ガウス

In [141]:
import numpy as np
from scipy.stats import multivariate_normal

x = np.mat([[0.0],
            [0.0]])
A = np.mat(np.random.rand(2,2))
Q = np.mat(np.random.rand(2,2))

X = [] # 状態
K = 500 # サンプル数
for i in range(K):
    x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
    X.append(x)

print("X_1\n%s\n" %X[0])

#mu=np.array([0, 0])
mu = X[0]
#covari = np.array([[ 1. , -0.5], [-0.5,  1.5]])
covari = np.mat([[ 1. , -0.5], [-0.5,  1.5]])
covari = Q
print(Q)
#y = multivariate_normal.pdf(X[1], mean=mu, cov=covari)

print("p_2\n%s\n" %y)
print(mu)
mu

X_1
[[-0.82294467]
 [-0.68311546]]

[[0.47200787 0.44140691]
 [0.14781448 0.85933781]]
p_2
[0.52812115 0.00267174]

[[-0.82294467]
 [-0.68311546]]


/mnt/nfs/takagi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ipykernel_launcher.py:12: RuntimeWarning: covariance is not positive-semidefinite.
  if sys.path[0] == '':


matrix([[-0.82294467],
        [-0.68311546]])

In [229]:
import numpy as np

#初期化
dt = 0.1

x = np.mat([[0.0],
            [0.0]])
A = np.mat([[1.0,dt],
            [0.0,1.0]])

Q = np.mat([[2,0.1],
            [0.1,2]])

X = [] # 状態
K = 500 # サンプル数
for i in range(K):
    x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
    X.append(x)

#多変量ガウス確率密度関数

mu = A*X[0]
cova = Q

print("A*X[0]\n%s\n" %mu)
print("covariance\n%s\n" %Q)
print("固有値", np.linalg.eig(Q))

#y = multivariate_normal.pdf(X[1], mean=mu, cov=cova)
print(y)
a = np.sqrt(np.linalg.det(Q)*(2*np.pi)**Q.ndim)

b = np.linalg.det((X[1]-mu).T * np.linalg.pinv(Q) * (X[1]-mu))
c = np.exp(b)/a

ln_c = b - np.log(a)
ln_c2 = b - (1/2)*(np.log(np.linalg.det(Q)) + Q.ndim*np.log(2*np.pi))

print()
print("a",a)
print()
print("a1", a1)
print()
print("b", b)
print()
print("多変量ガウス", c)
print("-----------------------------")
print(ln_c)
print(ln_c2)

A*X[0]
[[1.68452795]
 [0.43180416]]

covariance
[[2.  0.1]
 [0.1 2. ]]

固有値 (array([2.1, 1.9]), matrix([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))
[0.52812115 0.00267174]

a 12.550652821323126

a1 3.99

b 3.389019535982273

多変量ガウス 2.361381559028449
-----------------------------
0.8592468541220417
0.8592468541220417


In [230]:
import numpy as np

#初期化
dt = 0.1

x = np.mat([[0.0],
            [0.0]])
A = np.mat([[1.0,dt],
            [0.0,1.0]])

Q = np.mat([[2,0.1],
            [0.1,2]])

X = [] # 状態
K = 500 # サンプル数
for i in range(K):
    x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
    X.append(x)

#多変量ガウス確率密度関数

mu = A*X[0]
cova = Q

print("A*X[0]\n%s\n" %mu)
print("covariance\n%s\n" %Q)
print("固有値", np.linalg.eig(Q))

a = np.sqrt(np.linalg.det(Q)*(2*np.pi)**Q.ndim)
b = np.linalg.det((X[1]-mu).T * np.linalg.pinv(Q) * (X[1]-mu))
c = np.exp(b)/a

#対数化
ln_c = b - (1/2)*(np.log(np.linalg.det(Q)) + Q.ndim*np.log(2*np.pi))

print()
print("多変量ガウス", c)
print("-----------------------------")
print(ln_c)

A*X[0]
[[ 1.3641034 ]
 [-1.31447066]]

covariance
[[2.  0.1]
 [0.1 2. ]]

固有値 (array([2.1, 1.9]), matrix([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

多変量ガウス 0.11249110642672716
-----------------------------
-2.1848811144472404


### numpy　逆行列と擬似逆行列

In [191]:
import numpy as np

dt = 0.35

m = np.mat([[1.0,dt],
            [0.0,1.0]])

print("擬似逆行列\n%s\n" %np.linalg.pinv(m))
print("逆行列\n%s\n" %np.linalg.inv(m))
print("\n%s\n" %m.I)

擬似逆行列
[[ 1.00000000e+00 -3.50000000e-01]
 [-5.55111512e-17  1.00000000e+00]]

逆行列
[[ 1.   -0.35]
 [ 0.    1.  ]]


[[ 1.   -0.35]
 [ 0.    1.  ]]



In [253]:
import numpy as np

a = np.random.rand(2,2)
print(a[0,0])
print(a)

0.09612705624151296
[[0.09612706 0.12675116]
 [0.54418896 0.21448545]]


### numpy 単位行列

In [4]:
import numpy as np

a = np.mat(np.eye(2))
b = np.eye(2)
a

matrix([[1., 0.],
        [0., 1.]])

### numpy matrix 要素積

In [10]:
import numpy as np

A = np.mat(np.random.rand(2,2))
a = np.mat(np.eye(2))
print("乱数行列\n%s\n"%A)
print("単位行列\n%s\n"%a)

mat_mul = np.multiply(A, a)
mat_mul

乱数行列
[[0.7177083  0.39407245]
 [0.76231671 0.5926956 ]]

単位行列
[[1. 0.]
 [0. 1.]]



matrix([[0.7177083, 0.       ],
        [0.       , 0.5926956]])

#### 改行

In [13]:
i = 10
a = 5

print(a,"\n")
print(i)
print(i)

5 

10
10


### GPU計算 cupy

In [31]:
import cupy as cp
A = cp.arange(9).reshape(3, 3).astype('f') #cupy上で3*3の行列を生成
B = cp.arange(9).reshape(3, 3).astype('f') #cupy上で3*3の行列を生成
print('A = \n', A)
print('B = \n', B)

C = A + B #行列の和
print('和：A + B = \n', C)

D = cp.dot(A, B) #行列の内積
print('内積：A・B = \n', D)

A = 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
B = 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
和：A + B = 
 [[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
内積：A・B = 
 [[ 15.  18.  21.]
 [ 42.  54.  66.]
 [ 69.  90. 111.]]


In [36]:
import cupy as cp
import numpy as np
import time

#CPU計算
def numpy_sigmoid(x):
    return 1/(1+np.exp(-x))

start = time.time()
x = np.arange(3000000)
numpy_sigmoid(x)
print(time.time()-start)

#GPU計算
def cupy_sigmoid(x):
    return 1/(1+cp.exp(-x))

start = time.time()
x = cp.arange(3000000)
cupy_sigmoid(x)
print(time.time()-start)

0.07984733581542969
0.0009319782257080078


### cupyからnumpyの変換

In [48]:
import cupy as cp
import numpy as np

E = cp.arange(9).reshape(3, 3).astype('f') #cupyで生成するとcupy配列
print('「E」のクラスは', type(E)) 
print('cupy配列\n%s\n' %E)
print()

E_np = cp.asnumpy(E) #cupy ⇒ numpy配列へ変換
print('「E_np」のクラスは', type(E_np))
print('numpy配列に変換\n%s\n' %E_np)

E_cp = cp.asarray(E_np) #numpy ⇒ cupy配列へ変換
print('「E_cp」のクラスは', type(E_cp))
print('cupy配列に変換\n%s\n' %E_cp)

「E」のクラスは <class 'cupy.core.core.ndarray'>
cupy配列
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


「E_np」のクラスは <class 'numpy.ndarray'>
numpy配列に変換
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

「E_cp」のクラスは <class 'cupy.core.core.ndarray'>
cupy配列に変換
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]



### numpy arange

In [52]:
import numpy as np

x = np.arange(9).reshape(3, 3).astype('f')
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

### numpy ndarry 初期化

In [8]:
import numpy as np

a = np.zeros([3, 3])
b = np.mat(a)
b

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
import numpy as np

c = np.mat(np.eye(3, 3))
c[0, 0] = 2*c[0, 0]
c

matrix([[2., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
import numpy as np

dim = 2
x =np.mat(np.zeros([dim, dim-1]))

A = np.mat(np.eye(dim-1, dim))
A

matrix([[1., 0.]])

In [27]:
import numpy as np

x = np.ones((1, 5))
x

array([[1., 1., 1., 1., 1.]])

In [32]:
import numpy as np

a = np.array([[15, 10],[10, 10]])
e = np.linalg.eig(a)
e

LinAlgError: Last 2 dimensions of the array must be square

### cupyとnumpy比較　データ生成と行列演算

#### データ生成に関しても，行列演算に関しても，cupyは10000×10000で1000倍位早くなるが，100×100程度だとCPUの方が早い

In [6]:
import cupy as cp
import numpy as np
import time

#データ生成

start = time.time()
"""gpu_a = cp.arange(100000000).reshape(10000, 10000).astype('f') 
gpu_b = cp.arange(100000000).reshape(10000, 10000).astype('f')"""
gpu_a = cp.arange(10000).reshape(100, 100).astype('f') 
gpu_b = cp.arange(10000).reshape(100, 100).astype('f')
GPU_time = time.time()-start
print("GPUデータ生成時間\n%s\n" %GPU_time)

start = time.time()
"""cpu_a = np.arange(100000000).reshape(10000, 10000).astype('f') 
cpu_b = np.arange(100000000).reshape(10000, 10000).astype('f')"""
cpu_a = np.arange(10000).reshape(100, 100).astype('f') 
cpu_b = np.arange(10000).reshape(100, 100).astype('f')
CPU_time = time.time()-start
print("CPUデータ生成時間\n%s\n" %CPU_time)

print("===============================================================\n")
#行列の積算
print("積算\n")
start = time.time()
gpu_mat = cp.matmul(gpu_a, gpu_b)
GPU_mat_time = time.time()-start
print("GPU行列の積算時間\n%s\n" %GPU_mat_time)

start = time.time()
cpu_mat = np.matmul(cpu_a, cpu_b)
CPU_mat_time = time.time()-start
print("CPU行列の積算時間\n%s\n" %CPU_mat_time)

#行列の減算
print("減算\n")
start = time.time()
gpu_redu = gpu_a - gpu_b
GPU_redu_time = time.time()-start
print("GPU行列の減算時間\n%s\n" %GPU_redu_time)

start = time.time()
cpu_redu = cpu_a - cpu_b
CPU_redu_time = time.time()-start
print("CPU行列の減算時間\n%s\n" %CPU_redu_time)

#行列の加算
print("加算\n")
start = time.time()
gpu_add = gpu_a + gpu_b
GPU_add_time = time.time()-start
print("GPU行列の加算時間\n%s\n" %GPU_add_time)

start = time.time()
cpu_add = cpu_a + cpu_b
CPU_add_time = time.time()-start
print("CPU行列の加算時間\n%s\n" %CPU_add_time)

#行列の要素積
print("要素積\n")
start = time.time()
gpu_dot = gpu_a * gpu_b
GPU_dot_time = time.time()-start
print("GPU行列の要素積時間\n%s\n" %GPU_dot_time)

start = time.time()
cpu_dot = cpu_a * cpu_b
CPU_dot_time = time.time()-start
print("CPU行列の要素積時間\n%s\n" %CPU_dot_time)

GPUデータ生成時間
0.0006530284881591797

CPUデータ生成時間
0.0004639625549316406


積算

GPU行列の積算時間
0.0005435943603515625

CPU行列の積算時間
0.0010685920715332031

減算

GPU行列の減算時間
0.00019407272338867188

CPU行列の減算時間
0.0010247230529785156

加算

GPU行列の加算時間
0.00020003318786621094

CPU行列の加算時間
0.0011296272277832031

要素積

GPU行列の要素積時間
0.00018787384033203125

CPU行列の要素積時間
0.000997304916381836



### cupyからnumpyの変換　乱数Vr

In [7]:
import cupy as cp
import numpy as np

A = np.mat(np.random.rand(2,2))

A_cp = cp.asarray(A) #numpy ⇒ cupy配列へ変換
print('「A_cp」のクラスは', type(A_cp))
print('cupy配列に変換\n%s\n' %A_cp)

A_np = cp.asnumpy(A_cp) #cupy ⇒ numpy配列へ変換
print('「A_np」のクラスは', type(A_np))
print('numpy配列に変換\n%s\n' %A_np)


「A_cp」のクラスは <class 'cupy.core.core.ndarray'>
cupy配列に変換
[[0.72141087 0.97966824]
 [0.83717526 0.67251554]]

「A_np」のクラスは <class 'numpy.ndarray'>
numpy配列に変換
[[0.72141087 0.97966824]
 [0.83717526 0.67251554]]



### cupy配列

In [2]:
import cupy as cp

g = cp.array([[10, 11],[12, 13]])
g

array([[10, 11],
       [12, 13]])

### cupy逆行列 擬似逆行列

In [10]:
import cupy as cp

print(cp.__version__)
g = cp.array([[10, 11],[12, 13]])
g_in = cp.linalg.inv(g)
#g_in = cp.linalg.inv(g)
print(g_in)

4.3.0


RuntimeError: Current cupy only supports cusolver in CUDA 8.0

### numpy 擬似逆行列 エラー対策

In [25]:
import numpy as np

Q = np.mat([[10**15, 10**15, 20**15], [20**10, 10**10, 15**10], [25**10, 21**10, 13**10]])
Q = np.mat(np.random.rand(100, 100))
Q = np.eye(100)
Qi = np.linalg.pinv(Q)
Qi

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

### nanのとき，エラー表示

In [22]:
import numpy as np
#nan = float("nan")
a = np.log(-10)
print(a)
if(a == np.nan):
    print("error")

nan


/mnt/nfs/takagi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


### 多変量ガウス分布サンプル 

In [1]:
import numpy as np

mu = np.array([1, 2])
cov = np.array([[1, 0], [0, 1]])

"""mu = np.mat(np.array([1, 2]))
cov = np.mat(np.array([[1, 0], [0, 1]]))"""

x = np.random.multivariate_normal(mu, cov)
x

array([-0.47169268,  3.18630372])

### mat行列の積

In [10]:
import numpy as np

dms = 5
dmo = 10
dt = 0.1
x =np.mat(np.zeros([dms, 1]))
A = np.mat(np.eye(dms, dms))
C = np.mat(np.eye(dmo, dms))
Q = np.mat(np.eye(dms, dms))
R = np.mat(np.eye(dmo, dmo))
    
print("A\n%s\nC\n%s\nQ\n%s\nR\n%s" % (A, C, Q, R))
    
    
#x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
#y = C * x + np.mat(np.random.normal(0,1)).T
#y = C * x + np.mat(np.random.normal(np.zeros(dmo).tolist(),R)).T
y = C * x + np.mat(np.random.multivariate_normal(np.zeros(dmo).tolist(),R)).T
       
print("X\n%s\nY\n%s\n" % (x.shape, y.shape))

x_a = A * x
#x_b = np.mat(np.random.normal(np.zeros(dms).tolist(),Q)).T
x_b = np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(), Q)).T
print("x_a\n%s\nx_b\n%s\n" % (x_a.shape, x_b.shape))

y_a = C * x
#y_b = np.mat(np.random.normal(np.zeros(dmo).tolist(),R)).T
y_b = np.mat(np.random.multivariate_normal(np.zeros(dmo).tolist(), R)).T
print("y_a\n%s\ny_b\n%s\n" % (y_a.shape, y_b.shape))

A
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
C
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Q
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
R
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
X
(5, 1)
Y
(10, 1)

x_a
(5, 1)
x_b
(5, 1)

y_a
(10, 1)
y_b
(10, 1)



### 多変量ガウス確率密度関数

In [5]:
import numpy as np

dms = 5
dmo = 10

ums = np.mat(np.eye(dms))
umo = np.mat(np.eye(dmo))
    
A_u = np.mat(np.random.rand(dms,dms))
A = np.array(np.multiply(A_u, ums))
C = np.array(np.mat(np.random.rand(dmo,dms)))
    
Q_u = np.mat(np.random.rand(dms,dms))
Q = np.array(np.multiply(Q_u, ums))
R_u = np.mat(np.random.rand(dmo,dmo))
R = np.array(np.multiply(R_u, umo))

pi_1 = np.array(np.mat(np.random.rand(dms,1)))
V_1_u = np.mat(np.random.rand(dms,dms))
V_1 = np.array(np.multiply(V_1_u, ums))

In [7]:
x =np.mat(np.zeros([dms, 1]))

X = [] # 状態
Y = [] # 観測
K = 500 # サンプル数
for i in range(K):
    #x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
    #x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    #y = C * x + np.mat(np.random.normal(0,1)).T
    #y = C * x + np.mat(np.random.normal(np.zeros(dmo).tolist(),R)).T 
    x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    y = C * x + np.mat(np.random.multivariate_normal(np.zeros(dmo).tolist(),R)).T
    X.append(x)
    Y.append(y)   

In [8]:
from scipy.stats import multivariate_normal

y = multivariate_normal.pdf(X[0], mean=(pi_1.T)[0], cov=V_1)
y

array([6.31706605e-03, 1.33729811e-05, 6.36538054e-08, 2.78469186e-02,
       1.55946711e-06])

In [23]:
import numpy as np
from scipy.stats import multivariate_normal

#テストデータ生成(次元を自由に変更可能)
dms = 100
dmo = 100
dt = 0.1
ums = np.mat(np.eye(dms))
umo = np.mat(np.eye(dmo))

x =np.mat(np.zeros([dms, 1]))
A = np.mat(np.eye(dms, dms))
C = np.mat(np.eye(dmo, dms))
Q = np.mat(np.eye(dms, dms))
R = np.mat(np.eye(dmo, dmo))
pi_1 = np.mat(np.random.rand(dms,1))
V_1_u = np.mat(np.random.rand(dms,dms))
V_1 = np.multiply(V_1_u, ums)

"""print(len((pi_1.T)[0]))
print(len(pi_1))
print((pi_1.T)[0])
print(pi_1)"""
print(V_1.shape)
print(pi_1.shape)
print(x.shape)
print(V_1)
#print(x)
    
X = [] # 状態
Y = [] # 観測
K = 500 # サンプル数
for i in range(K):
    #x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
    #x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    #y = C * x + np.mat(np.random.normal(0,1)).T
    #y = C * x + np.mat(np.random.normal(np.zeros(dmo).tolist(),R)).T 
    x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    y = C * x + np.mat(np.random.multivariate_normal(np.zeros(dmo).tolist(),R)).T
    X.append(x)
    Y.append(y)

p = multivariate_normal.pdf(X[0].T, mean=pi_1[0], cov=V_1)
p

(100, 100)
(100, 1)
(100, 1)
[[0.15193257 0.         0.         ... 0.         0.         0.        ]
 [0.         0.05398564 0.         ... 0.         0.         0.        ]
 [0.         0.         0.34389798 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.43576512 0.         0.        ]
 [0.         0.         0.         ... 0.         0.3251632  0.        ]
 [0.         0.         0.         ... 0.         0.         0.92786132]]


ValueError: cannot reshape array of size 10000 into shape (1,1)

In [31]:
from scipy.stats import multivariate_normal
import numpy as np

x_e = np.array([[3], [2], [1]])
m_e = np.array([[3], [2], [1]])
c_e = np.array([[1, 3, 3], [2, 3, 4], [4, 6, 1]])

print(len(m_e[0]))

print(m_e[0])
print(c_e[0][0])

p = multivariate_normal.pdf(x_e, mean=m_e[0], cov=c_e[0][0])
p

1
[3]
1


array([0.39894228, 0.24197072, 0.05399097])

In [36]:
from scipy.stats import multivariate_normal
import numpy as np

N = 10
X = np.linspace(-4, 4, N)
pos = np.empty(X.shape + (2,))

mu_multi = np.array([0., 0.])
Sigma_multi = np.array([[ 1. , -0.5], [-0.5,  1.5]])

F = multivariate_normal(mu_multi, Sigma_multi)
p_multi = F.pdf(pos)
p_multi

array([0.14235251, 0.14235251, 0.14235251, 0.14235251, 0.14235251,
       0.14235251, 0.14235251, 0.14235251, 0.14235251, 0.14235251])

In [41]:
from scipy.stats import multivariate_normal
var = multivariate_normal(mean=[0,0], cov=[[1,0],[0,1]])
var.pdf([1,0])

0.09653235263005393

In [50]:
from scipy.stats import multivariate_normal
import numpy as np

mu_multi = np.array([0., 0.])
Sigma_multi = np.array([[ 1. , -0.5], [-0.5,  1.5]])

var = multivariate_normal(mean=mu_multi, cov=Sigma_multi)
var.pdf([1,0])

0.0781247131926453

In [63]:
from scipy.stats import multivariate_normal
import numpy as np

mu_multi = np.array([0., 0.])
Sigma_multi = np.array([[ 1. , -0.5], [-0.5,  1.5]])

mu_multi = np.mat([0., 0.]).tolist()
Sigma_multi = np.mat([[ 1. , -0.5], [-0.5,  1.5]]).tolist()

print(mu_multi)
print(Sigma_multi)
"""print(mu_multi.tolist())
print(Sigma_multi.tolist())"""

var = multivariate_normal(mean=mu_multi[0], cov=Sigma_multi)
var.pdf([1,0])

[[0.0, 0.0]]
[[1.0, -0.5], [-0.5, 1.5]]


0.0781247131926453

In [70]:
from scipy.stats import multivariate_normal
import numpy as np

mu_multi = np.mat([0., 0.])
Sigma_multi = np.mat([[ 1. , -0.5], [-0.5,  1.5]])

mu_multi_l = mu_multi.tolist()
Sigma_multi_l = Sigma_multi.tolist()

print(mu_multi)
print(Sigma_multi)
"""print(mu_multi.tolist())
print(Sigma_multi.tolist())"""

var = multivariate_normal(mean=mu_multi_l[0], cov=Sigma_multi_l)
var.logpdf([1,0])

[[0. 0.]]
[[ 1.  -0.5]
 [-0.5  1.5]]


-2.5494488420664503

In [56]:
from scipy.stats import multivariate_normal
import numpy as np

mu_multi = np.array(np.mat([0., 0.]).tolist())
Sigma_multi = np.array(np.mat([[ 1. , -0.5], [-0.5,  1.5]]).tolist())

var = multivariate_normal(mean=mu_multi, cov=Sigma_multi)
var.pdf([1,0])

ValueError: Array 'mean' must be a vector of length 2.

In [46]:
from scipy.stats import multivariate_normal
import numpy as np

mu_multi = np.mat(np.array([0., 0.]))
Sigma_multi = np.mat(np.array([[ 1. , -0.5], [-0.5,  1.5]]))

var = multivariate_normal(mean=mu_multi, cov=Sigma_multi)
var.pdf([1,0])

ValueError: Array 'mean' must be a vector of length 2.

### 多変量ガウス(新版)

In [71]:
from scipy.stats import multivariate_normal
import numpy as np

mu_multi = np.mat([0., 0.])
Sigma_multi = np.mat([[ 1. , -0.5], [-0.5,  1.5]])

mu_multi_l = mu_multi.tolist()
Sigma_multi_l = Sigma_multi.tolist()

print(mu_multi)
print(Sigma_multi)
"""print(mu_multi.tolist())
print(Sigma_multi.tolist())"""

var = multivariate_normal(mean=mu_multi_l[0], cov=Sigma_multi_l)
var.logpdf([1,0])

[[0. 0.]]
[[ 1.  -0.5]
 [-0.5  1.5]]


-2.5494488420664503

In [4]:
import numpy as np
from scipy.stats import multivariate_normal

#テストデータ生成(次元を自由に変更可能)
dms = 5
dmo = 5
dt = 0.1
ums = np.mat(np.eye(dms))
umo = np.mat(np.eye(dmo))

x =np.mat(np.zeros([dms, 1]))
A = np.mat(np.eye(dms, dms))
C = np.mat(np.eye(dmo, dms))
Q = np.mat(np.eye(dms, dms))
R = np.mat(np.eye(dmo, dmo))
pi_1 = np.mat(np.random.rand(dms,1))
V_1_u = np.mat(np.random.rand(dms,dms))
V_1 = np.multiply(V_1_u, ums)

"""print(len((pi_1.T)[0]))
print(len(pi_1))
print((pi_1.T)[0])
print(pi_1)"""
print(V_1.shape)
print(pi_1.shape)
print(x.shape)
print(V_1)
#print(x)
    
X = [] # 状態
Y = [] # 観測
K = 10 # サンプル数
for i in range(K):
    #x = A * x + np.mat(np.random.multivariate_normal((0,0),Q)).T
    #x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    #y = C * x + np.mat(np.random.normal(0,1)).T
    #y = C * x + np.mat(np.random.normal(np.zeros(dmo).tolist(),R)).T 
    x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    y = C * x + np.mat(np.random.multivariate_normal(np.zeros(dmo).tolist(),R)).T
    x_l = x.tolist()
    y_l = y.tolist()
    
    X.append(x_l)
    Y.append(y_l)

p = multivariate_normal(mean=pi_1[0], cov=V_1)
p.logpdf(X[0])    

(5, 5)
(5, 1)
(5, 1)
[[0.72209691 0.         0.         0.         0.        ]
 [0.         0.35925657 0.         0.         0.        ]
 [0.         0.         0.19666301 0.         0.        ]
 [0.         0.         0.         0.40092148 0.        ]
 [0.         0.         0.         0.         0.79609214]]


ValueError: cannot reshape array of size 25 into shape (1,1)

### 無限ループ

In [2]:
import numpy as np

a = 1
i = 0

while(1):
    a = a + 1
    print(i)
    
    if(a > 10):
        break
    
    i = i + 1


0
1
2
3
4
5
6
7
8
9


### ファイル保存の上書き阻止のためのループごとに名前を変える

In [2]:
import os

N = 10

for i in range(N):
    print("img_"+str(i)+"/file")


img_0/file
img_1/file
img_2/file
img_3/file
img_4/file
img_5/file
img_6/file
img_7/file
img_8/file
img_9/file


### リスト内の要素を選んで，その要素がリスト内で何番目か取得する．

In [28]:
import numpy as np
import random

batch_size = 3

ind = random.sample(range(10), batch_size)
print("index\n%s\n" %ind)

#a = np.random.rand(10).tolist()
a = np.random.rand(10)
print("リストa\n%s\n" %a)

b = [a[i] for i in ind ]

b

index
[9, 0, 5]

リストa
[0.83135415 0.60218402 0.33465264 0.18142314 0.82473213 0.08991363
 0.64184529 0.42127435 0.26905297 0.90680775]



[0.906807747793139, 0.831354149124171, 0.08991362951743531]

### 引数の無い関数

In [5]:
import numpy as np

def a_add():
    a = 5
    return a

y = 10 + a_add()
y

15