# 学習済みのinverter

### データ読み込みのための関数(バッチ)

In [4]:
import tensorflow as tf
import numpy as np
import random as ra
import os
import glob
from numpy.random import *
import time

def batch(batch_size):
    #batch_size = 60

    #再構成した画像のPATHのリスト
    path_rec = "/opt/pfw/dragon_ball_reconsted/reconsted/disc11/story3/*.npy"
    filelists_rec = glob.glob(path_rec, recursive=True)

    #zのPATHのリスト
    path_z = "/opt/pfw/dragon_ball_reconsted/z/disc11/story3/*.npy"
    filelists_z = glob.glob(path_z, recursive=True)

    #サンプルしてくるインデックスのリスト
    ind = ra.sample(range(len(filelists_rec)), batch_size)

    #サンプルしてくるインデックスの各PATHを格納したリスト
    batch_images_rec = [filelists_rec[i] for i in ind ]
    batch_images_z = [filelists_z[i] for i in ind ]

    #再構成した画像とzの各バッチ
    batch_x = np.array([np.load(f).tolist() for f in batch_images_rec]) #再構成画像のファイル読み込み
    batch_z = np.array([np.load(f).tolist() for f in batch_images_z]) #zのファイル読み込み
    
    return batch_x, batch_z

In [7]:
import tensorflow as tf
import numpy as np
import random as ra
import os
import glob
from numpy.random import *
import time

start = time.time()

n_epochs = 50000000
training_loss = []
eps = 0.01
batch_size = 1
batch_x, batch_z = batch(batch_size)
kp_p = 1.0

epo = 60000

g2 = tf.Graph()
with tf.Session(graph=g2) as sess:
    #計算グラフの復元
    new_saver = tf.train.import_meta_graph('./savepoint/inverter_graph/train_epoch_'+str(epo)+'/trained-model.meta')
    #実行フェーズでの値の復元
    new_saver.restore(sess, './savepoint/inverter_graph/train_epoch_'+str(epo)+'/trained-model')
    
    loss = sess.run('loss/loss:0', feed_dict={'Placeholder:0' : batch_x, 'Placeholder_1:0' : batch_z, 'Placeholder_2:0' : kp_p})
    train_step = sess.run('train/Adam', feed_dict={'Placeholder:0' : batch_x, 'Placeholder_1:0' : batch_z, 'Placeholder_2:0' : kp_p})
    y = sess.run('fully4/add:0', feed_dict={'Placeholder:0' : batch_x, 'Placeholder_1:0' : batch_z, 'Placeholder_2:0' : kp_p})
    print(loss)
    print(train_step)
    print(y.shape)
    #print(y)
y

INFO:tensorflow:Restoring parameters from ./savepoint/inverter_graph/train_epoch_60000/trained-model
121.88
None
(1, 100)


array([[ 0.00953451,  0.0307411 ,  0.04841327, -0.08912477, -0.00367212,
         0.01107763,  0.02331166,  0.19427101,  0.01636336,  0.03547521,
         0.27695984,  0.00467675,  0.01041173,  0.02888585, -0.04662186,
         0.02019877, -0.20774083,  0.23417857, -0.04925729,  0.02213304,
         0.0191018 , -0.06105234,  0.01366773,  0.02749317, -0.05714776,
         0.01737077,  0.12659313,  0.0084565 ,  0.02046099, -0.03062566,
         0.21234687, -0.00666096, -0.00066855,  0.0187257 ,  0.1757189 ,
         0.02381668, -0.20937061,  0.02915876,  0.02929257,  0.03760717,
        -0.00633414,  0.01858837, -0.01943819,  0.01024514, -0.00047842,
        -0.07171699, -0.02979955, -0.00224349,  0.04704698,  0.09441631,
         0.02106768, -0.0331798 ,  0.15268654,  0.02800318,  0.03271685,
        -0.06585322,  0.01947626,  0.03168476,  0.01800863,  0.00937171,
         0.02423463,  0.02875223,  0.00256147,  0.02498393,  0.01952708,
         0.00688007,  0.01408795,  0.00200796,  0.0

### テストデータの生成(選定した動画を使う)

In [16]:
import tensorflow as tf
import numpy as np
import random as ra
import os
import glob
from numpy.random import *
import time

batch_size = 60

def batch(batch_size):
    #batch_size = 60

    #再構成した画像のPATHのリスト
    path_rec = "/opt/pfw/dragon_ball_reconsted/reconsted/disc11/story3/*.npy"
    filelists_rec = glob.glob(path_rec, recursive=True)
    print(len(filelists_rec))

    #zのPATHのリスト
    path_z = "/opt/pfw/dragon_ball_reconsted/z/disc11/story3/*.npy"
    filelists_z = glob.glob(path_z, recursive=True)
    print(len(filelists_z))

    #サンプルしてくるインデックスのリスト(クリリンのデータのindex)
    ind = []
    i = 898
    while(1):
        ind.append(i)
        i = i+1
        if(i > 1200):
            break
    print(ind)
    
    #サンプルしてくるインデックスの各PATHを格納したリスト
    batch_images_rec = [filelists_rec[i] for i in ind ]
    batch_images_z = [filelists_z[i] for i in ind ]

    #再構成した画像とzの各バッチ
    batch_x = np.array([np.load(f).tolist() for f in batch_images_rec]) #再構成画像のファイル読み込み
    batch_z = np.array([np.load(f).tolist() for f in batch_images_z]) #zのファイル読み込み
    
    return batch_x, batch_z

#batch_x, batch_z = batch(batch_size)

In [17]:
import tensorflow as tf
import numpy as np
import random as ra
import os
import glob
from numpy.random import *
import time

start = time.time()

n_epochs = 50000000
training_loss = []
eps = 0.01
batch_size = 1
batch_x, batch_z = batch(batch_size)
kp_p = 1.0

epo = 60000

g2 = tf.Graph()
with tf.Session(graph=g2) as sess:
    #計算グラフの復元
    new_saver = tf.train.import_meta_graph('./savepoint/inverter_graph/train_epoch_'+str(epo)+'/trained-model.meta')
    #実行フェーズでの値の復元
    new_saver.restore(sess, './savepoint/inverter_graph/train_epoch_'+str(epo)+'/trained-model')
    
    loss = sess.run('loss/loss:0', feed_dict={'Placeholder:0' : batch_x, 'Placeholder_1:0' : batch_z, 'Placeholder_2:0' : kp_p})
    train_step = sess.run('train/Adam', feed_dict={'Placeholder:0' : batch_x, 'Placeholder_1:0' : batch_z, 'Placeholder_2:0' : kp_p})
    y = sess.run('fully4/add:0', feed_dict={'Placeholder:0' : batch_x, 'Placeholder_1:0' : batch_z, 'Placeholder_2:0' : kp_p})
    print(loss)
    print(train_step)
    print(y.shape)
    #print(y)
y

42854
42854
[898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 107

array([[ 0.00953583,  0.03073959,  0.04841126, ..., -0.04643112,
        -0.05462735,  0.00792682],
       [ 0.00953583,  0.03073959,  0.04841126, ..., -0.04643112,
        -0.05462735,  0.00792682],
       [ 0.00953583,  0.03073959,  0.04841126, ..., -0.04643112,
        -0.05462735,  0.00792682],
       ..., 
       [ 0.00953583,  0.03073959,  0.04841126, ..., -0.04643112,
        -0.05462735,  0.00792682],
       [ 0.00953583,  0.03073959,  0.04841126, ..., -0.04643112,
        -0.05462735,  0.00792682],
       [ 0.00953583,  0.03073959,  0.04841126, ..., -0.04643112,
        -0.05462735,  0.00792682]], dtype=float32)

In [28]:
print(len(y[0]))
print(len(y))
y[0]

100
303


array([ 0.00953583,  0.03073959,  0.04841126, -0.08912443, -0.00366896,
        0.01107523,  0.02330996,  0.19427341,  0.01636409,  0.0354729 ,
        0.27695122,  0.00467552,  0.0104119 ,  0.02888443, -0.04659704,
        0.02019764, -0.2077367 ,  0.23417743, -0.04926359,  0.02213626,
        0.01910026, -0.0610526 ,  0.01366673,  0.02749078, -0.05714435,
        0.01737012,  0.12659231,  0.00845952,  0.02046065, -0.03062916,
        0.21233311, -0.00666334, -0.0006662 ,  0.01873057,  0.17571205,
        0.02381505, -0.2093676 ,  0.02915475,  0.02929306,  0.03760639,
       -0.00633434,  0.01859134, -0.01943806,  0.01024536, -0.00046861,
       -0.07169482, -0.02980214, -0.00224469,  0.04704423,  0.0944192 ,
        0.02106553, -0.03317888,  0.15267985,  0.02800331,  0.03272066,
       -0.06585484,  0.01947527,  0.03168437,  0.01800701,  0.00937015,
        0.02423237,  0.02875237,  0.00256073,  0.024985  ,  0.01952176,
        0.00687983,  0.01408372,  0.00201059,  0.00118781,  0.00

## LDSの入力データ作成

In [29]:
import numpy as np

ind = []
i = 898
while(1):
    ind.append(i)
    i = i+1
    if(i > 1200):
        break
print(len(ind))

for j in range(len(ind)):
    np.save('/mnt/nfs/takagi/Mastercorse_program/Picture_future_world/inverter_LDS/USING/LDS_input/di11_sry3_sce4_Cririn/img_'+str(ind[j])+'_z.npy', y[j])

303


In [44]:
import numpy as np

ind = []
i = 898
while(1):
    ind.append(i)
    i = i+1
    if(i > 1200):
        break
Y=[]
for j in range(len(ind)):
    img_z = np.load('/mnt/nfs/takagi/Mastercorse_program/Picture_future_world/inverter_LDS/USING/LDS_input/di11_sry3_sce4_Cririn/img_'+str(ind[j])+'_z.npy')
    img_z_mat = np.mat(img_z)
    Y.append(img_z_mat.T)

print(Y[0].dtype)
print(Y[0].shape)
print(Y[0])

float32
(100, 1)
[[ 0.00953583]
 [ 0.03073959]
 [ 0.04841126]
 [-0.08912443]
 [-0.00366896]
 [ 0.01107523]
 [ 0.02330996]
 [ 0.19427341]
 [ 0.01636409]
 [ 0.0354729 ]
 [ 0.27695122]
 [ 0.00467552]
 [ 0.0104119 ]
 [ 0.02888443]
 [-0.04659704]
 [ 0.02019764]
 [-0.2077367 ]
 [ 0.23417743]
 [-0.04926359]
 [ 0.02213626]
 [ 0.01910026]
 [-0.0610526 ]
 [ 0.01366673]
 [ 0.02749078]
 [-0.05714435]
 [ 0.01737012]
 [ 0.12659231]
 [ 0.00845952]
 [ 0.02046065]
 [-0.03062916]
 [ 0.21233311]
 [-0.00666334]
 [-0.0006662 ]
 [ 0.01873057]
 [ 0.17571205]
 [ 0.02381505]
 [-0.2093676 ]
 [ 0.02915475]
 [ 0.02929306]
 [ 0.03760639]
 [-0.00633434]
 [ 0.01859134]
 [-0.01943806]
 [ 0.01024536]
 [-0.00046861]
 [-0.07169482]
 [-0.02980214]
 [-0.00224469]
 [ 0.04704423]
 [ 0.0944192 ]
 [ 0.02106553]
 [-0.03317888]
 [ 0.15267985]
 [ 0.02800331]
 [ 0.03272066]
 [-0.06585484]
 [ 0.01947527]
 [ 0.03168437]
 [ 0.01800701]
 [ 0.00937015]
 [ 0.02423237]
 [ 0.02875237]
 [ 0.00256073]
 [ 0.024985  ]
 [ 0.01952176]
 [ 0.006

In [41]:
import numpy as np

dms = 100
dmo = 100
dt = 0.1
x =np.mat(np.zeros([dms, 1]))
A = np.mat(np.eye(dms, dms))
C = np.mat(np.eye(dmo, dms))
Q = np.mat(np.eye(dms, dms))
R = np.mat(np.eye(dmo, dmo))
    
#print("A\n%s\nC\n%s\nQ\n%s\nR\n%s" % (A, C, Q, R))
    
X = [] # 状態
Y = [] # 観測
K = 500 # サンプル数
for i in range(K):
    x = A * x + np.mat(np.random.multivariate_normal(np.zeros(dms).tolist(),Q)).T
    y = C * x + np.mat(np.random.multivariate_normal(np.zeros(dmo).tolist(),R)).T
    X.append(x)
    Y.append(y)

print(Y[0].dtype)
print(Y[0].shape)
print(Y[0])

float64
(100, 1)
[[-0.8555483 ]
 [ 0.45969465]
 [ 0.09905538]
 [ 0.72545197]
 [ 1.61104584]
 [-0.59295008]
 [-3.50500016]
 [ 2.89317583]
 [ 2.25022023]
 [-0.08809212]
 [ 1.23746634]
 [-0.62429133]
 [-1.33571881]
 [-0.82418635]
 [ 0.67269396]
 [-0.20740279]
 [-0.1928766 ]
 [-0.25434984]
 [ 2.20930866]
 [ 0.87045643]
 [ 2.15433896]
 [ 0.79687008]
 [-0.13308129]
 [-1.24337916]
 [-0.075297  ]
 [-1.45252638]
 [ 0.35192191]
 [-0.06977557]
 [-0.35428504]
 [ 3.26807273]
 [-0.10477834]
 [-0.80414649]
 [ 1.53388864]
 [-2.19610299]
 [ 1.77148439]
 [-1.85178169]
 [ 0.84446787]
 [-0.7278737 ]
 [-0.42498893]
 [ 0.12115465]
 [-0.81159654]
 [ 1.08201464]
 [-0.18100702]
 [-1.52301848]
 [-1.50389751]
 [ 1.22595861]
 [ 1.00323846]
 [-3.42658373]
 [ 0.95648194]
 [-0.59520279]
 [-1.43630923]
 [-0.94643937]
 [ 0.29768131]
 [-0.26405972]
 [ 1.22076588]
 [ 0.07271225]
 [ 0.3171292 ]
 [ 0.92515723]
 [ 0.34736995]
 [-0.5440912 ]
 [-2.26147955]
 [-1.13522553]
 [-2.55793086]
 [-1.04894332]
 [-2.28351527]
 [-0.374